### ISSUE TITLE
scaled node name with wrong domainname

### ISSUE THREAD

**Issue by suridaddy** [IBM/cloudland#161]
#### When adding new nodes to the existing openshift cluster, wrong node name generated as below,
<img width="710" alt="image" src="https://user-images.githubusercontent.com/19152153/96099189-8d9c0e80-0f05-11eb-90f8-531280ae7f02.png">

#### Actual node name:
`worker-2.eti.cdl.ibm.com` 

#### Expected node name:
`worker-2.ec-ocp45.eti.cdl.ibm.com`

**Comment by Catherine2019** [comment]
Fixed
