### ISSUE TITLE
network not available after run allinone.sh

### ISSUE THREAD

**Issue by liuhaocg** [IBM/cloudland#19]
after run allinone.sh using cland user, network is down
And I tried to restart network, it works few seconds, after that, down again.
![image](https://user-images.githubusercontent.com/16176401/59975275-26a86700-95e9-11e9-8b53-5f0b10ab5f6b.png)

**Comment by Catherine2019** [comment]
Can you show me some more information like
ifconfig
nmcli connection show
ip link show
brctl show

**Comment by liuhaocg** [comment]
open new issue to summary problems I met.
close this issue.
