### ISSUE TITLE
Multiple hypervisors and more IPs type issue

### ISSUE THREAD

**Issue by liuhaocg** [IBM/cloudland#21]
Tried to user the 3rd way to set my network, but `Error: Failed to modify connection 'enp2s0': ipv4.dns: this property is not allowed for 'method=disabled'` happened. 
And check ip add found device br5000 not UP `br5000: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 46:da:ef:2c:6d:3f brd ff:ff:ff:ff:ff:ff
    inet 192.168.168.202/24 brd 192.168.168.255 scope global noprefixroute br5000
       valid_lft forever preferred_lft forever` shown the network device start up failed.
My network config is `TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
BOOTPROTO="static"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="enp2s0"
DEVICE="enp2s0"
ONBOOT="yes"
IPADDR="192.168.168.202"
PREFIX="24"
DNS1="192.168.168.1"
GATEWAY="192.168.168.1"
IPV6_PRIVACY="no"
`

**Comment by Catherine2019** [comment]
There are few conditions conflicting with each other when trying to modify the parameter of a nic with nmcli, testing more on this.

**Comment by Catherine2019** [comment]
Covered by the document
