### ISSUE TITLE
Hypervisor - z/VM: CPU resource calculation

### ISSUE THREAD

**Issue by jinlings** [IBM/cloudland#230]
Currently, we setup the default initial is 8G, we will identify which hyper will be dispatched by the amount of all guest +8G, it's not a good idea, so we will adopt new way to do that

**Comment by xieqiang2020** [comment]
Use [Feilong RESTful API ](https://cloudlib4zvm.readthedocs.io/en/latest/restapi.html#get-host-info) to get vcpus.
