### ISSUE TITLE
Install Hyper in KVM and ZVM

### ISSUE THREAD

**Issue by jinlings** [IBM/cloudland#233]
Different steps to Install Hyper  between KVM and ZVM,such as cloudlet, we are unable to deploy it automatically by Ansible, and need to improve

**Comment by xieqiang2020** [comment]
Finished:
1. Build sci, cloudland, clui, libvirt-console-proxy: test done
2. RPM package built via rpmbuild: test done
3. Post script of the RPM package: coding done
4. Deploy controller via Ansible: coding done

Testing:
1. Install cloudland RPM in a bare-metal VM to deploy the controller
2. Use Ansible to deploy the hyper nodes

**Comment by xieqiang2020** [comment]
PR has been submitted.
