### ISSUE TITLE
Auto-refresh works wrongly(back to first page) in instance panel

### ISSUE THREAD

**Issue by suridaddy** [IBM/cloudland#264]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/19152153/111935102-b3a18c80-8afd-11eb-9a09-69fd713ecb96.png">

**Reproduce steps:**
- Go to instance panel
- Jump to other page, like, 2nd page
- Wait ~2 seconds, current page will be refreshed to 1st page

**Comment by jnanbj** [comment]
fixed. add offset to request for auto-refresh
