### ISSUE TITLE
OpenShift VM hostname naming convention

### ISSUE THREAD

**Issue by suridaddy** [IBM/cloudland#54]
<%cluster_name%>-master<N>
<%cluster_name%>-worker<N>
<%cluster_name%>-lb

**Comment by Catherine2019** [comment]
The FQDN of names will be
lb.<%cluster_name%>.<%base_domain%>
master-N.<%cluster_name%>.<%base_domain%>
worker-N.<%cluster_name%>.<%base_domain%>
master and worker's naming convention is from the official doc https://docs.openshift.com/container-platform/4.2/installing/installing_bare_metal/installing-bare-metal.html#installation-dns-user-infra_installing-bare-metal, will change loadbalancer name from oc##-lb to lb
