### ISSUE TITLE
Install integration with noVNC into allinone.sh

### ISSUE THREAD

**Issue by Catherine2019** [IBM/cloudland#79]
1. copy noVNC static files into web/clui/public
2. install and configure libvirt-console-proxy
3. test on the installation

**Comment by wenshilin** [comment]
function novnc_install()
{
VNC_HOST="localhost"
PORT="6080"
VNC_DEST="localhost:5900"
proxy_pid=""

cleanup() {
    trap - TERM QUIT INT EXIT
    trap "true" CHLD   # Ignore cleanup messages
    echo
    if [ -n "${proxy_pid}" ]; then
        echo "Terminating WebSockets proxy (${proxy_pid})"
        kill ${proxy_pid}
    fi
}

sudo ./opt/cloundland/web/clui/public/noVNC/utils/launch.sh - -vnc VNC_DEST

echo -e "\n\nNavigate to this URL:\n"
if [ "x$SSLONLY" == "x" ]; then
    echo -e "    http://$(VNC_HOST=):${PORT}/vnc.html?host=$(VNC_HOST=)&port=${PORT}\n"
else
    echo -e "    https://$(VNC_HOST=):${PORT}/vnc.html?host=$(VNC_HOST=)&port=${PORT}\n"
fi
}

**Comment by wenshilin** [comment]
# Install libvirt console proxy
function inst_console_proxy()
{
    sudo yum -y install libvirt-devel
    cd /opt
    _**sudo git clone https://github.com/novnc/noVNC.git
    sudo mv noVNC/ /opt/cloudland/web/clui/public/novnc/
    echo "Copy succeed"**_
    sudo git clone https://github.com/libvirt/libvirt-console-proxy.git
    sudo chown cland.cland libvirt-console-proxy
    cd libvirt-console-proxy
    go build -o build/virtconsoleproxyd cmd/virtconsoleproxyd/virtconsoleproxyd.go
    cert_dir=/opt/libvirt-console-proxy/cert
    mkdir $cert_dir
    net_dev=$(cat $net_conf | grep 'network_device:' | cut -d: -f2)
    myip=$(ifconfig $net_dev | grep 'inet ' | awk '{print $2}')
    cat >/tmp/ca.info <<EOF
cn = console-proxy
ca
cert_signing_key
EOF
    cd $cert_dir
    certtool --generate-privkey >cakey.pem
    certtool --generate-self-signed --load-privkey cakey.pem --template /tmp/ca.info --outfile cacert.pem
    certtool --generate-privkey >serverkey.pem
    cat <<EOF > /tmp/server.info
organization = console-proxy
cn = $myip
tls_www_server
encryption_key
signing_key
EOF
certtool --generate-certificate --load-privkey serverkey.pem --load-ca-certificate cacert.pem --load-ca-privkey cakey.pem --template /tmp/server.info --outfile servercert.pem
    rm -f /tmp/ca.info
}

**Comment by wenshilin** [comment]
cd /opt
sudo git clone https://github.com/novnc/noVNC.git
sudo mv noVNC/ /opt/cloudland/web/clui/public/novnc/
echo "Copy succeed"

**Comment by Catherine2019** [comment]
Done
