### ISSUE TITLE
Broken links within docs

### ISSUE THREAD

**Issue by heyawhite** [IBM/cloudland#82]
Hey there, 

I noticed you have references to documentation with broken links. It's possible this is porting to a website and therefore this isn't useful... but in case it's not, the `.md` is missing in a number of places. For example:

- [Operations guide](https://github.com/IBM/cloudland/blob/master/doc/Operation.md): at end of the article you link to the Deployment guide without `.md`
- [Deployment](https://github.com/IBM/cloudland/blob/master/doc/Deployment.md): at the end of the article you link to Operations without `.md`

Separately, in the main README:

> Visit [doc](https://github.com/IBM/cloudland/doc) for full documentation and guide.

The link for docs should be `https://github.com/IBM/cloudland/tree/master/doc`

**Comment by Catherine2019** [comment]
Thanks, will fix it

**Comment by Catherine2019** [comment]
Fixed :)
